application: dubious-demo # duby-primer
version: duby
runtime: java
public_root: /public

resource_files:
  - exclude: /build/**

static_files:
  - include: /**/*.ico
    expiration: 365d
  - include: /**/*.gif
    expiration: 365d
  - include: /**/*.jpeg
    expiration: 365d
  - include: /**/*.jpg
    expiration: 365d
  - include: /**/*.png
    expiration: 365d
  - include: /**/*.js
    expiration: 365d
  - include: /**/*.css
    expiration: 365d

handlers:
  - url: /info/properties
    servlet: controllers.InfoPropertiesController
    name: info_properties

  - url: /contacts/*
    servlet: controllers.ContactsController
    name: contacts

  - url: /source/*
    servlet: controllers.SourceController
    name: source

  - url: /simple_duby/*
    servlet: testing.SimpleDuby
    name: dimple_duby

  - url: /simple_java/*
    servlet: testing.SimpleJava
    name: simple_java